### ISSUE TITLE
Is this code compatible with matlab clone octave?

### ISSUE THREAD

**Issue by stefano2734** [dreamlot/COSMOL2OpenFOAM#1]

**Comment by dreamlot** [comment]
This program uses 'parfor' to parallelize some computations. Octave hasn't added this function to its roster yet. You will need to replace 'parfor' with the regular 'for' if you want to run it in Octave.

**Comment by stefano2734** [comment]
it is fine that serial run is simple possible with this little change in octave.

parallel is more limited available for octave.
http://wiki.octave.org/Parallel_package
See https://blog.dominodatalab.com/simple-parallelization/

Perhaps it goes with parallel_package, but you are the expert for your code.
I am only a User of Software.

**Comment by dreamlot** [comment]
Rewriting the program in cpp would accelerate it much more than parallelizing it in Matlab or Octave. However, the project finished before I could finish debugging the cpp vesrion, lol.

**Comment by stefano2734** [comment]
There is also a new dragonfly project to bring perhaps parfor more simple to octave.
https://www.sciencedirect.com/science/article/pii/S1477842417300660
https://github.com/DragonflyTeam/dragonfly

**Comment by stefano2734** [comment]
The project is actual in gitlab
https://gitlab.com/dragonflytool/dragonfly

**Comment by dreamlot** [comment]
That's cool.
> The project is actual in gitlab
> https://gitlab.com/dragonflytool/dragonfly
